import type { IconType } from 'react-icons';
import {
  SiCss,
  SiDocker,
  SiDotnet,
  SiFastapi,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiTailwindcss,
} from 'react-icons/si';
import {
  TbApi,
  TbBrain,
  TbBrandCSharp,
  TbDatabase,
  TbFileSearch,
  TbPlugConnected,
  TbPrompt,
  TbRobot,
  TbSpider,
  TbSql,
} from 'react-icons/tb';

// Logo for each skill in config/content.ts; concepts without a brand get a neutral symbol.
export const skillIcons: Record<string, IconType> = {
  Python: SiPython,
  JavaScript: SiJavascript,
  SQL: TbSql,
  'C#': TbBrandCSharp,
  'AI Agents': TbRobot,
  'Large Language Models (LLMs)': TbBrain,
  'LLM API Integration': TbPlugConnected,
  'Prompt Engineering': TbPrompt,
  'Web Scraping': TbSpider,
  'Data Extraction': TbFileSearch,
  FastAPI: SiFastapi,
  'Node.js': SiNodedotjs,
  '.NET': SiDotnet,
  'RESTful APIs': TbApi,
  React: SiReact,
  'Tailwind CSS': SiTailwindcss,
  HTML: SiHtml5,
  CSS: SiCss,
  PostgreSQL: SiPostgresql,
  NoSQL: TbDatabase,
  Docker: SiDocker,
  Git: SiGit,
  GitHub: SiGithub,
};
